export const effectsList = [
  {
    id: "basic",
    name: "Basic",
    effects: [
      { id: "brightness", name: "Brightness Adjustment" },
      { id: "contrast", name: "Contrast Enhancement" },
      { id: "saturation-boost", name: "Saturation Boost" },
      { id: "desaturation", name: "Desaturation" },
      { id: "hue-shift", name: "Hue Shift" },
      { id: "black-white", name: "Black & White" },
      { id: "sepia", name: "Sepia Tone" },
      { id: "vintage-film", name: "Vintage Film" },
      { id: "hdr", name: "HDR" },
      { id: "cross-process", name: "Cross-Process" },
    ],
  },
  {
    id: "enhance",
    name: "Enhance",
    effects: [
      { id: "sharpen", name: "Sharpen" },
      { id: "noise-reduction", name: "Noise Reduction" },
      { id: "clarity", name: "Clarity" },
      { id: "vignette", name: "Vignette" },
      { id: "soft-focus", name: "Soft Focus" },
    ],
  },
  {
    id: "portrait",
    name: "Portrait",
    effects: [
      { id: "age-progression", name: "Age Progression" },
      { id: "age-regression", name: "Age Regression" },
      { id: "gender-swap", name: "Gender Swap" },
      { id: "facial-hair", name: "Facial Hair Addition" },
      { id: "hairstyle-change", name: "Hairstyle Change" },
      { id: "skin-smoothing", name: "Skin Smoothing" },
      { id: "teeth-whitening", name: "Teeth Whitening" },
      { id: "eye-brightening", name: "Eye Brightening" },
      { id: "lip-color", name: "Lip Color Change" },
      { id: "hair-color", name: "Hair Color Change" },
    ],
  },
  {
    id: "artistic",
    name: "Artistic",
    effects: [
      { id: "cartoonify", name: "Cartoonify" },
      { id: "sketch", name: "Sketch" },
      { id: "pop-art", name: "Pop Art" },
      { id: "watercolor", name: "Watercolor" },
      { id: "oil-painting", name: "Oil Painting" },
      { id: "charcoal", name: "Charcoal Sketch" },
      { id: "pointillism", name: "Pointillism" },
      { id: "impressionism", name: "Impressionism" },
    ],
  },
  {
    id: "distort",
    name: "Distort",
    effects: [
      { id: "pixelate", name: "Pixelate" },
      { id: "mosaic", name: "Mosaic" },
      { id: "glitch", name: "Glitch" },
      { id: "hologram", name: "Hologram" },
      { id: "cyberpunk", name: "Cyberpunk" },
      { id: "neon-glow", name: "Neon Glow" },
    ],
  },
  {
    id: "advanced",
    name: "Advanced",
    effects: [
      { id: "face-swap", name: "Face Swap" },
      { id: "expression-change", name: "Expression Change" },
      { id: "background-removal", name: "Background Removal" },
      { id: "style-transfer", name: "Style Transfer" },
      { id: "deep-dream", name: "Deep Dream" },
    ],
  },
  {
    id: "composition",
    name: "Composition",
    effects: [
      { id: "panorama", name: "Panorama" },
      { id: "tilt-shift", name: "Tilt-Shift" },
      { id: "double-exposure", name: "Double Exposure" },
      { id: "collage", name: "Collage" },
    ],
  },
  {
    id: "transform",
    name: "Transform",
    effects: [
      { id: "rotate", name: "Rotate" },
      { id: "flip", name: "Flip" },
      { id: "crop", name: "Crop" },
      { id: "straighten", name: "Straighten" },
      { id: "perspective", name: "Perspective Correction" },
    ],
  },
  {
    id: "overlay",
    name: "Overlay",
    effects: [
      { id: "text-overlay", name: "Text Overlay" },
      { id: "stickers", name: "Stickers" },
      { id: "frames", name: "Frames" },
      { id: "logo-overlay", name: "Logo Overlay" },
      { id: "watermark", name: "Watermark" },
    ],
  },
  {
    id: "theme",
    name: "Theme",
    effects: [
      { id: "halloween", name: "Halloween" },
      { id: "christmas", name: "Christmas" },
      { id: "birthday", name: "Birthday" },
      { id: "wedding", name: "Wedding" },
      { id: "vacation", name: "Vacation" },
    ],
  },
  {
    id: "vintage",
    name: "Vintage",
    effects: [
      { id: "vhs", name: "VHS" },
      { id: "film-grain", name: "Film Grain" },
      { id: "polaroid", name: "Polaroid" },
      { id: "disposable-camera", name: "Disposable Camera" },
      { id: "old-tv", name: "Old TV" },
    ],
  },
  {
    id: "art-style",
    name: "Art Style",
    effects: [
      { id: "abstract", name: "Abstract" },
      { id: "surreal", name: "Surreal" },
      { id: "minimalist", name: "Minimalist" },
      { id: "cubism", name: "Cubism" },
      { id: "expressionism", name: "Expressionism" },
    ],
  },
  {
    id: "professional",
    name: "Professional",
    effects: [
      { id: "medical", name: "Medical" },
      { id: "architectural", name: "Architectural" },
      { id: "fashion", name: "Fashion" },
      { id: "food", name: "Food" },
      { id: "automotive", name: "Automotive" },
      { id: "real-estate", name: "HDR for Real Estate" },
      { id: "virtual-staging", name: "Virtual Staging" },
      { id: "sky-replacement", name: "Sky Replacement" },
    ],
  },
  {
    id: "nature",
    name: "Nature",
    effects: [
      { id: "animal-filters", name: "Animal Filters" },
      { id: "nature-overlay", name: "Nature Overlay" },
      { id: "weather-effects", name: "Weather Effects" },
      { id: "landscape", name: "Landscape Transformation" },
      { id: "underwater", name: "Underwater" },
    ],
  },
]

